spring:
  http:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      VERSION: v1
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registryFetchIntervalSeconds: 10
    disable-delta: true
zuul:
  addHostHeader: true
  routes:
    devops:
      path: /devops/**
      serviceId: devops-service
    iam:
      path: /iam/**
      serviceId: iam-service
    oauth:
      path: /oauth/**
      sensitiveHeaders:
      serviceId: oauth-server
      stripPrefix: false
    notify:
      path: /notify/**
      serviceId: notify-service
    asgard:
      path: /asgard/**
      serviceId: asgard-service
    manager:
      path: /manager/**
      serviceId: manager-service
    file:
      path: /file/**
      serviceId: file-service
    org:
      path: /org/**
      serviceId: organization-service
  semaphore:
    max-semaphores: 300
  sensitiveHeaders: Cookie,Set-Cookie
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
choerodon:
  gateway:
    helper:
      helper-skip-paths: /oauth/**, /manager/swagger-ui.html, /manager/swagger-resources/**, /manager/webjars/**, /manager/docs/**
      service-id: gateway-helper
      enabled: true
      enabled-jwt-log: false
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  httpclient:
    enabled: false
  okhttp:
    enabled: true
management:
  port: 8081
  security:
    enabled: false
security:
  basic:
    enabled: false
