spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      VERSION: v1
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registryFetchIntervalSeconds: 10
    disable-delta: true
zuul:
  addHostHeader: true
  routes:
    iam:
      path: /iam/**
      serviceId: iam-service
    oauth:
      path: /oauth/**
      serviceId: oauth-server
      stripPrefix: false
      sensitiveHeaders: none
    notify:
      path: /notify/**
      serviceId: notify-service
    asgard:
      path: /asgard/**
      serviceId: asgard-service
    manager:
      path: /manager/**
      serviceId: manager-service
    file:
      path: /file/**
      serviceId: file-service
    org:
      path: /org/**
      serviceId: organization-service
    devops:
      path: /devops/**
      serviceId: devops-service
    agile:
      path: /agile/**
      serviceId: agile-service
    state:
      path: /state/**
      serviceId: state-machine-service
    issue:
      path: /issue/**
      serviceId: issue-service
    test-manager:
      path: /test/**
      serviceId: test-manager-service
    wiki:
      path: /wiki/**
      serviceId: wiki-service
    apim:
      path: /apim/**
      serviceId: apim-service
  semaphore:
    max-semaphores: 300
  sensitiveHeaders: Cookie,Set-Cookie
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000
choerodon:
  gateway:
    allowed:
      origin: '*'
    helper:
      service-id: gateway-helper
      enabled: true
      enabled-jwt-log: false
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  httpclient:
    enabled: false
  okhttp:
    enabled: true